[package]
name = "post-client"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.18"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.45"
# post-server = {path = "../post-server" }